export * from "./change-major-plan.js";
export * from "./check.js";
export * from "./course-table.js";
export * from "./create-archive.js";
export * from "./exam-place.js";
export * from "./info.js";
export * from "./login.js";
export * from "./student-archive.js";
export * from "./test-query.js";
