name: Build Artifacts

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install project
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Generate Files
        run: |
          cd dist/
          echo "blacklist
          cache/
          data" > ./.gitignore
          echo '{"name":"innenu-private","type":"module"}' > ./package.json
          cp -r ../public .

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: deploy
          folder: dist

  deploy-server:
    runs-on: ubuntu-latest
    needs: deploy-github
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: deploy
          fetch-depth: 0

      - name: Configuration environment
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan mister-hope.com >> ~/.ssh/known_hosts
          git config --global user.name 'Mr.Hope'
          git config --global user.email 'mister-hope@outlook.com'

      - name: Deploy
        run: |
          git push -f git@mister-hope.com:/www/wwwroot/innenu-service deploy
          ssh git@mister-hope.com "cd /www/wwwroot/innenu-service && git reset --hard HEAD"
