name: Build and Deploy Artifacts

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install project
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Generate Files
        run: |
          cd dist/
          echo "blacklist
          cache/
          data" > ./.gitignore
          echo '{"name":"innenu-private","type":"module"}' > ./package.json
          cp -r ../public .

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: deploy
          folder: dist
          single-commit: true

      - name: Trigger Hook
        run: curl -s "${{ secrets.BT_WEBHOOK_URL }}"
